apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
data:
  config.js: |
    var config = (() => {
    return {
        "VUE_APP_TITLE":"kubenates run",
        "VUE_APP_API_BACKEND":"http://localhost:8000/api"
      };
    })();