name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
        
    - name: Build  Frontend image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        # relative path to the place where source code with Dockerfile is located
        context: ./frontend
        # Note: tags has to be all lower-case
        tags: |
           rdddocker/favm_frontend:latest
        # build on feature branches, push only on main branch
        push: ${{ github.ref == 'refs/heads/main' }}
    
    - name: Build  Backend image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        # relative path to the place where source code with Dockerfile is located
        context: ./backend
        # Note: tags has to be all lower-case
        tags: |
          rdddocker/favm_backend:latest
        # build on feature branches, push only on main branch
        push: ${{ github.ref == 'refs/heads/main' }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
